/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    tutorialSidebar: [
        'intro',
        {
            type: 'category',
            label: 'Foundation',
            items: [
                'foundation/setup',
                'foundation/plop',
                'foundation/templates',
                'foundation/link',
                'foundation/complete'
            ]
        },
        {
            type: 'category',
            label: 'Templates',
            items: [
                {
                    type: 'doc',
                    label: 'React component (TS)',
                    id: 'templates/ts-component'
                },
                'templates/remix-route',
                {
                    type: 'doc',
                    label: 'Tiny React App',
                    id: 'templates/tiny-react'
                },
                'templates/use-state-machine'
            ]
        },
        {
            type: 'link',
            label: 'Plop.js',
            href: 'https://plopjs.com'
        },
        {
            type: 'link',
            label: 'Inquirer prompts',
            href: 'https://github.com/SBoudrias/Inquirer.js/tree/master#readme'
        }
    ]
};

module.exports = sidebars;
